[package]
name = "dbt_node_selector"
version = "0.1.2"
description = "dbt Node Selector library (In Development)"
license = "Apache 2.0"
repository = "https://github.com/heysweet/select_nodes"

[[module]]
name = "dbt_node_selector"
source = "target/wapm/dbt_node_selector.wasm"
